FROM node:19

WORKDIR /app

# Copy package.json and package-lock.json
COPY ./ip-asset-management-ui/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY ./ip-asset-management-ui/ ./

# Build the application
RUN npm run build

# Install a simple HTTP server for serving static content
RUN npm install -g serve

# Expose the port the app runs on
EXPOSE 3000

# Serve the app
CMD ["serve", "-s", "build", "-l", "3000"]