version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ipam
    networks:
      - ipam-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ipam-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=ipam
    networks:
      - ipam-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ipam-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ipam-network

networks:
  ipam-network:
    driver: bridge

volumes:
  mongodb_data: